name: Shiny Gallery
description: Gallery of Shiny example applications
permalink: /apps/:title.html
url: http://shinygallery.com
baseurl: ''
exclude: 
  - COPYING
  - import.R
  - README.md 
  - shiny-gallery.Rproj
  - src






