name: Shiny Gallery
description: Gallery of Shiny example applications
permalink: /apps/:title.html
url: http://rstudio.github.io/shiny-gallery
baseurl: /shiny-gallery
exclude: 
  - README.md 
  - shiny-gallery.Rproj





